<?php

require_once dirname(__FILE__) . '/../lib.inc.php';

/**
 * Test class for WebLib.
 * Generated by PHPUnit on 2013-07-14 at 14:31:58.
 */
class WebLibTest extends PHPUnit_Framework_TestCase {

  /**
   * @var WebLib
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new WebLib;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers WebLib::GeneratePassword
   * @todo Implement testGeneratePassword().
   */
  public function testGeneratePassword() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::Html5Header
   * @todo Implement testHtml5Header().
   */
  public function testHtml5Header() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::JQueryInclude
   * @todo Implement testJQueryInclude().
   */
  public function testJQueryInclude() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::IncludeJS
   * @todo Implement testIncludeJS().
   */
  public function testIncludeJS() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::IncludeCSS
   * @todo Implement testIncludeCSS().
   */
  public function testIncludeCSS() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::InitHTML5page
   * @todo Implement testInitHTML5page().
   */
  public function testInitHTML5page() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::GetVal
   * @todo Implement testGetVal().
   */
  public function testGetVal() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::ToDate
   * @todo Implement testToDate().
   */
  public function testToDate() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::ToDBDate
   * @todo Implement testToDBDate().
   */
  public function testToDBDate() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::RandStr
   * @todo Implement testRandStr().
   */
  public function testRandStr() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::GetAbsoluteURLFolder
   * @todo Implement testGetAbsoluteURLFolder().
   */
  public function testGetAbsoluteURLFolder() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::InpSanitize
   * @todo Implement testInpSanitize().
   */
  public function testInpSanitize() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::ShowMsg
   * @todo Implement testShowMsg().
   */
  public function testShowMsg() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::PageInfo
   * @todo Implement testPageInfo().
   */
  public function testPageInfo() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::FooterInfo
   * @todo Implement testFooterInfo().
   */
  public function testFooterInfo() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::CreateDB
   * @todo Implement testCreateDB().
   */
  public function testCreateDB() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::CheckAuth
   * @todo Implement testCheckAuth().
   */
  public function testCheckAuth() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::InitSess
   * @todo Implement testInitSess().
   */
  public function testInitSess() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::AuthSession
   * @todo Implement testAuthSession().
   */
  public function testAuthSession() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::ShowMenuBar
   * @todo Implement testShowMenuBar().
   */
  public function testShowMenuBar() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::ShowMenuitem
   * @todo Implement testShowMenuitem().
   */
  public function testShowMenuitem() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::StaticCaptcha
   * @todo Implement testStaticCaptcha().
   */
  public function testStaticCaptcha() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers WebLib::StaticCaptcha
   * @todo Implement testStaticCaptcha().
   */
  public function testLeafNodes() {
    $i = 0;
    $Tree = array();
    $Tree[$i]['P'] = 0;
    $Tree[$i++]['C'] = 1;
    $Tree[$i]['P'] = 1;
    $Tree[$i++]['C'] = 2;
    $Tree[$i]['P'] = 2;
    $Tree[$i++]['C'] = 3;
    $Tree[$i]['P'] = 2;
    $Tree[$i++]['C'] = 4;
    $Tree[$i]['P'] = 4;
    $Tree[$i++]['C'] = 5;
    $Tree[$i]['P'] = 3;
    $Tree[$i++]['C'] = 6;
    $Tree[$i]['P'] = 6;
    $Tree[$i++]['C'] = 7;
    $Tree[$i]['P'] = 7;
    $Tree[$i++]['C'] = 8;
    $Tree[$i]['P'] = 5;
    $Tree[$i++]['C'] = 9;
    $Tree[$i]['P'] = 1;
    $Tree[$i++]['C'] = 10;
    $Tree[$i]['P'] = 2;
    $Tree[$i++]['C'] = 11;
    $Tree[$i]['P'] = 10;
    $Tree[$i++]['C'] = 12;

    $Leafs = '';
    $this->object->LeafNodes($Tree, 0, $Leafs);
    $this->assertEquals($Leafs, '8,9,11,12,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 1, $Leafs);
    $this->assertEquals($Leafs, '8,9,11,12,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 2, $Leafs);
    $this->assertEquals($Leafs, '8,9,11,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 3, $Leafs);
    $this->assertEquals($Leafs, '8,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 4, $Leafs);
    $this->assertEquals($Leafs, '9,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 5, $Leafs);
    $this->assertEquals($Leafs, '9,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 6, $Leafs);
    $this->assertEquals($Leafs, '8,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 7, $Leafs);
    $this->assertEquals($Leafs, '8,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 8, $Leafs);
    $this->assertEquals($Leafs, '8,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 9, $Leafs);
    $this->assertEquals($Leafs, '9,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 10, $Leafs);
    $this->assertEquals($Leafs, '12,');

    $Leafs = '';
    $this->object->LeafNodes($Tree, 11, $Leafs);
    $this->assertEquals($Leafs, '11,');
  }

}

?>
